const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');
const output=process.env.QA_OUTPUT || '/tmp/verto-qa';fs.mkdirSync(output,{recursive:true});
const base=process.env.QA_BASE||'http://localhost:8000/';
const pages=process.env.QA_ROUTES ? JSON.parse(process.env.QA_ROUTES) : ['','projects.html','services.html','studio.html','lead-agent.html','cases/master-tyres.html','cases/lead-desk.html','privacy.html','personal-data-consent.html','terms.html','404.html','projects/morrow-coffee/','projects/apex-detailing/','projects/forma-estate/','projects/auren-dental/','projects/nord-cabin/','projects/noir-golf/','projects/otklik/'];
const widths=base.startsWith('http://localhost')?[320,375,390,430,768,1280,1440,1920]:[390,1440];
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});const out={base,checks:[],errors:[],interactions:[]};
for(const route of pages){for(const width of widths){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push('JS: '+e.message));p.on('console',e=>{if(e.type()==='error')errors.push('console: '+e.text())});p.on('requestfailed',r=>{if(!r.failure()?.errorText.includes('ERR_ABORTED'))errors.push('network: '+r.url()+' '+r.failure()?.errorText)});p.on('response',r=>{if(r.status()>=400&&!(route==='404.html'&&r.request().isNavigationRequest()))errors.push('HTTP '+r.status()+': '+r.url())});
try{const response=await p.goto(base+route,{waitUntil:'networkidle',timeout:30000});await p.evaluate(()=>document.fonts.ready);let overflow=[];let h=await p.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<h;y+=1000){await p.evaluate(y=>scrollTo(0,y),y);await p.waitForTimeout(80);const o=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));if(o.sw>o.cw+1)overflow.push({y,...o})}await p.waitForFunction(()=>[...document.images].every(i=>i.complete),null,{timeout:15000}).catch(()=>{});const info=await p.evaluate(()=>({h1:document.querySelectorAll('h1').length,title:document.title,images:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),anchors:[...document.querySelectorAll('a[href^="#"]')].filter(a=>a.hash.length>1&&!document.getElementById(decodeURIComponent(a.hash.slice(1)))).map(a=>a.hash),canonical:document.querySelector('link[rel="canonical"]')?.href}));if(info.images.length)errors.push('broken images: '+info.images.join(','));if(info.anchors.length)errors.push('anchors: '+info.anchors.join(','));if(info.h1!==1)errors.push('H1 count '+info.h1);if(overflow.length)errors.push('overflow '+JSON.stringify(overflow));out.checks.push({route,width,status:response.status(),...info,overflow});if(width===390||width===1440){await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:output+'/' +(base.startsWith('http://localhost')?'local':'production')+'-'+(route.replaceAll('/','-').replace('.html','')||'home')+'-'+width+'.png',fullPage:true})}if(errors.length)out.errors.push({route,width,errors});}catch(e){out.errors.push({route,width,errors:[e.message]})}await p.close()}fs.writeFileSync(output+'/' +(base.startsWith('http://localhost')?'local':'production')+'-report.json',JSON.stringify(out,null,2));console.log('Checked '+(route||'home'));}
const p=await b.newPage({viewport:{width:390,height:844}});await p.goto(base);await p.locator('[data-menu-toggle]').click();if(await p.locator('[data-navigation]').getAttribute('data-open')!=='1')throw Error('menu did not open');await p.keyboard.press('Escape');if(await p.locator('[data-menu-toggle]').getAttribute('aria-expanded')!=='false')throw Error('Escape did not close menu');await p.locator('[data-menu-toggle]').click();await p.locator('[data-navigation] a').first().click();await p.waitForURL('**/projects.html');out.interactions.push('mobile menu + Escape + navigation PASS');for(const [f,count]of [['case',1],['product',3],['demo',6],['all',10]]){await p.locator(`[data-filter="${f}"]`).click();if(await p.locator('[data-project]:visible').count()!==count)throw Error('filter '+f);};out.interactions.push('all four project filters PASS');await p.goto(base);await p.locator('[data-reel-open]').click();await p.waitForFunction(()=>document.querySelector('#reel-dialog video').readyState>=2);await p.keyboard.press('Escape');if(await p.locator('#reel-dialog').evaluate(d=>d.open))throw Error('reel close');out.interactions.push('showreel loads + closes + restores focus PASS');await p.locator('.faq-list summary').first().click();if(await p.locator('.faq-list details').first().getAttribute('open')===null)throw Error('FAQ');out.interactions.push('FAQ PASS');await p.locator('[data-brief="Редизайн"]').click();if(!(await p.locator('[data-brief-link]').getAttribute('href')).includes('text='))throw Error('brief');out.interactions.push('brief creates draft link without sending PASS');await p.evaluate(()=>scrollTo(0,0));await p.locator('[data-motion-toggle]').click();if(!await p.locator('[data-motion-video]').evaluate(v=>v.paused))throw Error('motion pause');out.interactions.push('motion pause PASS');await p.close();
const no=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await no.goto(base);const opacity=await no.locator('#work .section-head').evaluate(el=>getComputedStyle(el).opacity);if(opacity!=='1')throw Error('no JS hidden content');out.interactions.push('content visible without JavaScript PASS');await no.close();
fs.writeFileSync(output+'/' +(base.startsWith('http://localhost')?'local':'production')+'-report.json',JSON.stringify(out,null,2));console.log(JSON.stringify({pages:out.checks.length,errors:out.errors,interactions:out.interactions},null,2));await b.close();if(out.errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
