const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
process.chdir(require('path').resolve(__dirname, '..'));
(async()=>{
 const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage();await p.goto(process.env.QA_BASE || 'http://localhost:8000/');
 const result=await p.evaluate(async()=>{
  const c=document.createElement('canvas');c.width=960;c.height=960;const ctx=c.getContext('2d');
  function pt(u,v,t){const r=238+v*Math.cos(u*1.5);let x=r*Math.cos(u),y=r*Math.sin(u),z=v*Math.sin(u*1.5)+35*Math.sin(u*3);const a=.55+Math.sin(t)*.4,by=t;let yy=y*Math.cos(a)-z*Math.sin(a),zz=y*Math.sin(a)+z*Math.cos(a);return [x*Math.cos(by)+zz*Math.sin(by),yy,-x*Math.sin(by)+zz*Math.cos(by)];}
  function draw(t){ctx.fillStyle='#0a0a0b';ctx.fillRect(0,0,960,960);const g=ctx.createRadialGradient(480,440,60,480,480,500);g.addColorStop(0,'#242120');g.addColorStop(1,'#0a0a0b');ctx.fillStyle=g;ctx.fillRect(0,0,960,960);
   const faces=[];const project=p=>{const d=1000/(1100-p[2]);return [480+p[0]*d*1.32,465+p[1]*d*1.32]};
   for(let i=0;i<200;i++)for(let j=0;j<14;j++){const u=i/200*Math.PI*2,v=-89+j/14*178;const ps=[pt(u,v,t),pt(u+Math.PI/100,v,t),pt(u+Math.PI/100,v+178/14,t),pt(u,v+178/14,t)];const a=ps[0],d=ps[1].map((x,k)=>x-a[k]),e=ps[3].map((x,k)=>x-a[k]);let n=[d[1]*e[2]-d[2]*e[1],d[2]*e[0]-d[0]*e[2],d[0]*e[1]-d[1]*e[0]];let l=Math.hypot(...n);n=n.map(x=>x/l);if(n[2]<0)n=n.map(x=>-x);const diffuse=Math.max(0,n[0]*-.35+n[1]*-.65+n[2]*.65),spec=Math.pow(Math.max(0,n[0]*-.22+n[1]*-.42+n[2]*.88),22);const shine=.2+.65*diffuse;const copper=(Math.sin(u*2+t)+1)/2;const base=[160+70*copper,155-50*copper,150-76*copper];const rgb=base.map(x=>Math.min(255,x*shine+130*spec));faces.push({ps,z:ps.reduce((a,p)=>a+p[2],0)/4,col:`rgb(${rgb.join(',')})`});}
   faces.sort((a,b)=>a.z-b.z);faces.forEach(f=>{ctx.beginPath();f.ps.map(project).forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=f.col;ctx.fill();ctx.strokeStyle=f.col;ctx.lineWidth=.5;ctx.stroke()});
  }
  draw(.5);const poster=c.toDataURL('image/jpeg',.9);const stream=c.captureStream(30);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:2200000});let chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();const start=performance.now();await new Promise(resolve=>{function frame(now){draw((now-start)/8000*Math.PI*2+.5);if(now-start<8000)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)});const ended=new Promise(r=>recorder.onstop=r);recorder.stop();await ended;const data=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(new Blob(chunks,{type:'video/webm'}))});return {poster,data};
 });
 fs.writeFileSync('assets/motion/verto-ribbon.webm',Buffer.from(result.data.split(',')[1],'base64'));fs.writeFileSync('assets/motion/verto-ribbon.jpg',Buffer.from(result.poster.split(',')[1],'base64'));
 // An original, silent portfolio reel using only the studio's existing images.
 const reel=await p.evaluate(async()=>{const images=await Promise.all(['master-tires/hero.png','portfolio/morrow-preview-v2.jpg','portfolio/apex-preview-v2.jpg','portfolio/forma-preview-v2.jpg'].map(async src=>{const im=new Image();im.src='./assets/'+src;await im.decode();return im}));const names=['MASTER TIRES','MORROW COFFEE','APEX DETAILING','FORMA ESTATE'];const c=document.createElement('canvas');c.width=1440;c.height=810;const x=c.getContext('2d');
 function draw(ms){const k=Math.min(3,Math.floor(ms/3000)),progress=ms%3000/3000;x.fillStyle='#171717';x.fillRect(0,0,1440,810);const im=images[k];const scale=Math.max(1440/im.width,810/im.height)*(1.02+progress*.06);x.drawImage(im,(1440-im.width*scale)/2,(810-im.height*scale)/2,im.width*scale,im.height*scale);const g=x.createLinearGradient(0,350,0,810);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(0,0,0,.9)');x.fillStyle=g;x.fillRect(0,0,1440,810);x.fillStyle='#f2eee8';x.font='bold 64px sans-serif';x.fillText(names[k],70,693);x.font='20px sans-serif';x.fillText(k===0?'CASE STUDY / WEB DESIGN & DEVELOPMENT':'VERTO STUDIO / DESIGN CONCEPT',74,735);x.fillText('VERTO / SELECTED WORK',74,66);x.fillRect(74,770,1292*progress,2)}
 x.drawImage(images[1],0,0,1440,810);const poster=c.toDataURL('image/jpeg',.9);const recorder=new MediaRecorder(c.captureStream(30),{mimeType:'video/webm;codecs=vp9',videoBitsPerSecond:2600000});const chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.start();const start=performance.now();await new Promise(r=>{function tick(now){draw(now-start);if(now-start<11950)requestAnimationFrame(tick);else r()}requestAnimationFrame(tick)});const stopped=new Promise(r=>recorder.onstop=r);recorder.stop();await stopped;const data=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(new Blob(chunks,{type:'video/webm'}))});return {poster,data}});
 fs.writeFileSync('assets/motion/verto-showreel.webm',Buffer.from(reel.data.split(',')[1],'base64'));fs.writeFileSync('assets/motion/verto-showreel.jpg',Buffer.from(reel.poster.split(',')[1],'base64'));await b.close();
})()
